# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/4/


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 9c55a9ffd7b8ce40a4721ff0146d173371d93cfc

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###
DELETE {{baseUrl}}/advertisements/3/
Authorization: Token 211112363796da78a26fbd0a17a38bf934629c81
###
# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 9c55a9ffd7b8ce40a4721ff0146d173371d93cfc

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
