<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-05 08:33

=======
>>>>>>> da34ece7ad16c6ca2ff424630ef67e03ef525b02
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('description', models.CharField(blank=True, max_length=10)),
=======
                ('description', models.CharField(blank=True, max_length=200)),
>>>>>>> da34ece7ad16c6ca2ff424630ef67e03ef525b02
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor')),
            ],
        ),
    ]
